apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity: 
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany - not good for hostPath
    # - ReadWriteMany
  hostPath:
    path: /data
    type: DirectoryOrCreate